language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

before_script:
  - npm install -g codecov

script:
  - npm run test:unit:cover
  - codecov --token=$CODECOV_TOKEN

deploy:
  - provider: pages
    local-dir: docs/.vuepress/dist
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    email: 751674443@qq.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: zech126/aggregate
